name: Run Tofu Plan on File Changes

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/main.tf'  # Adjust the file pattern to match the files you want to watch for changes
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/main.tf'
  workflow_dispatch:
jobs:
  run-tofu-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: OpenTofu # Prepares OpenTofu - downloading the alpha required
      uses: opentofu/setup-opentofu@v1.0.3
      with:
          tofu_version: 1.8.0-alpha1

    - name: Deploy infrastructure
        # The code below imports the variables made available, then allows them to be used by Tofu by prefixing with TF_VAR_
      run: |
        tofu init 
    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - name: Run Tofu Plan
      run: tofu plan  # Replace with the command to run Tofu Plan
