name: Run Tofu Plan on File Changes

on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
  pull_request:
    branches:
      - main
    paths:
      - 'main.tf'
  workflow_dispatch:
  
jobs:
  run-tofu-plan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: OpenTofu
      uses: opentofu/setup-opentofu@v1.0.3
      with:
          tofu_version: 1.8.0-alpha1

    - name: Deploy infrastructure
      run: |
        tofu init 
        
    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        
    - name: Run Tofu Plan
      run: tofu plan
      
    - name: Run Tofu Apply
      run: tofu apply -auto-approve
