name: Run Tofu Plan on File Changes

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/main.tf'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/main.tf'

jobs:
  run-tofu-plan:
    runs-on: macos-10.15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Initialize Tofu
      run: tofu init
      
    - name: Run Tofu Plan
      run: tofu plan
