name: Run Tofu Plan on File Changes

on:
  push:
    paths:
      - 'terraform/main.tf'  # Adjust the file pattern to match the files you want to watch for changes
  pull_request:
    paths:
      - 'terraform/main.tf'

jobs:
  run-tofu-plan:
    runs-on: macos-10.15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Initialize Tofu
      run: tofu init  
      
    - name: Run Tofu Plan
      run: tofu plan 
